; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

;audio guestbook 
[env:teensy41-guestbook]
platform = teensy
board = teensy41
framework = arduino
upload_protocol = teensy-gui
;upload_protocol = teensy-cli

;build_flags = -D USB_MTPDISK

;button logic test program
[env:teensy41-button-test]
platform = teensy
board = teensy41
framework = arduino
upload_protocol = teensy-gui
build_src_filter = +<../button-test>

;Set RTC time (only run when connected to the internet!)
[env:teensy41-set-rtc]
platform = teensy
board = teensy41
framework = arduino
upload_protocol = teensy-gui
build_src_filter = +<../rtc-test>

;ESP32 admin monitoring program - web page availabe via wi-fi (assuming mains power availabe)
;giving up-to-date information about the audio guestbook usage and status.
[env:admin-monitor]
platform = espressif32
;board = esp32-s3-devkitc-1
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps = 
    ESP32Async/AsyncTCP @ 3.5.0
    ESP32Async/ESpAsyncWebServer @ 3.12.0
build_src_filter = +<../admin-monitor>

;ESP32 admin server. Serves the same function as the admin-monitor application but uses ESP-NOW
;to coummunicate to a ESP-NOW receiver (audio-guestbook-admin-viewer) which is a 
;Waveshare AMOLED 1.43" round display.
[env:esp-now-admin-server]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps = 

; required for upload and serial reading
build_flags =
   -DARDUINO_USB_MODE=1
   -DARDUINO_USB_CDC_ON_BOOT=1

; set frequency to 80MHz to save power/overheating
board_build.f_cpu = 80000000L

board_build.arduino.memory_type = qio_qspi
board_build.flash_mode = qio
board_build.psram_type = qio
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
board_build.partitions = default.csv
board_build.extra_flags = 
  -DBOARD_HAS_PSRAM
upload_protocol = esptool
upload_speed = 921600
build_src_filter = +<..esp-now-admin-server>
